Repository OpenVoxProject/openbolt, pull requests merged in 2025-07, with the labels that each got.

#6 Bump minimal required Ruby from 2.5->3.2
  bolt.gemspec
Labels: backwards-incompatible

#11 Rename gem to openbolt
  .github/release.yml
  .github/workflows/gem_release.yaml
  .github/workflows/prepare_release.yml
  .github/workflows/release.yml
  CODEOWNERS
  Gemfile
  README.md
  lib/bolt/applicator.rb
  openbolt.gemspec
Labels: backwards-incompatible

#22 Readme minor updates
  README.md
Labels: documentation, skip-changelog

#31 CI: Fix broken dita jobs
  .github/workflows/docs.yaml
  .github/workflows/tests.yaml
Labels: skip-changelog

#34 CI: Set explicit token permissions
  .github/workflows/apply.yaml
  .github/workflows/bolt_spec.yaml
  .github/workflows/docker_transport.yaml
  .github/workflows/linux.yaml
  .github/workflows/modules.yaml
  .github/workflows/publish-powershell-module.yaml
  .github/workflows/pwsh.yaml
  .github/workflows/schemas.yaml
  .github/workflows/ssh_transport.yaml
  .github/workflows/windows.yaml
  .github/workflows/winrm_transport.yaml
Labels: skip-changelog

#38 Allow hiera-eyaml 4.x
  openbolt.gemspec
Labels: enhancement

#39 Allow minitar 1.x
  openbolt.gemspec
Labels: enhancement

#40 Allow ruby_smb 2.x and 3.x
  openbolt.gemspec
Labels: enhancement
